SAA-466 Updated all deps
SparkPost/eslint-config-sparkpost pull request #33
Opened 2022-01-19 17:50 UTC by gwalls

2022-01-21 20:39 UTC, gwalls commented on index.js
> +      extends: [
•100% ➜ eslint . --fix-dry-run
Error: ESLint configuration in sparkpost/index is invalid:
        - Unexpected top-level property "overrides[1].extends".

Referenced from: /Users/gwalls/workspace/eslint-config-sparkpost/api.js
Referenced from: /Users/gwalls/workspace/metrics-api/.eslintrc.json
    at validateConfigSchema (/Users/gwalls/workspace/metrics-api/node_modules/eslint/lib/config/config-validator.js:235:15)
    at Object.validate (/Users/gwalls/workspace/metrics-api/node_modules/eslint/lib/config/config-validator.js:261:5)
    at loadFromDisk (/Users/gwalls/workspace/metrics-api/node_modules/eslint/lib/config/config-file.js:544:19)
    at load (/Users/gwalls/workspace/metrics-api/node_modules/eslint/lib/config/config-file.js:587:20)
    at /Users/gwalls/workspace/metrics-api/node_modules/eslint/lib/config/config-file.js:453:36
    at Array.reduceRight (<anonymous>)
    at applyExtends (/Users/gwalls/workspace/metrics-api/node_modules/eslint/lib/config/config-file.js:431:26)
    at loadFromDisk (/Users/gwalls/workspace/metrics-api/node_modules/eslint/lib/config/config-file.js:551:22)
    at load (/Users/gwalls/workspace/metrics-api/node_modules/eslint/lib/config/config-file.js:587:20)
    at /Users/gwalls/workspace/metrics-api/node_modules/eslint/lib/config/config-file.js:453:36

2022-01-24 20:40 UTC, beardyman requested changes

2022-01-27 18:40 UTC, beardyman commented
closes #24 
closes #29 
closes #30 
closes #31 
closes #32

2022-01-31 19:57 UTC, rosadajake approved these changes

2022-01-31 21:19 UTC, beardyman approved these changes

2022-01-31 21:20 UTC, merged